remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
title: Попова Наталья
description: Портфолио

# Навигация
header_pages:
- index.md
- contacts.md

# Социальные ссылки (опционально)
social:
  github: username
  linkedin: username
  email: natalia@example.com